"""updated the attendance model

Revision ID: 38db3ef11d12
Revises: b4f32f7d4fa7
Create Date: 2025-03-11 10:09:52.096058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38db3ef11d12'
down_revision = 'b4f32f7d4fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('clock_out_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('application_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('application_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('clock_out_time',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
