"""modification of ththe token blacklist model

Revision ID: ad98f880e689
Revises: 40d376db6d47
Create Date: 2025-03-05 16:03:16.551614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad98f880e689'
down_revision = '40d376db6d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_token_blacklist_jti', ['jti'])  # Provide a name for the constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint('uq_token_blacklist_jti', type_='unique')  # Drop the named constraint
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
