"""updated the leave model by adding the application_date

Revision ID: b4f32f7d4fa7
Revises: 4b4aea53b53d
Create Date: 2025-03-10 15:49:33.429111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f32f7d4fa7'
down_revision = '4b4aea53b53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('application_date')

    # ### end Alembic commands ###
