"""updated the name password_hash

Revision ID: da0f0f31cac6
Revises: 9534fbfd44a5
Create Date: 2025-02-21 13:07:48.794600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0f0f31cac6'
down_revision = '9534fbfd44a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=10000), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=10000), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
